# Generated by Django 5.1.1 on 2024-09-18 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='email_client',
            field=models.ManyToManyField(to='distribution.client', verbose_name='получатели'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активная рассылка'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.message', verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='имя получателя'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='period',
            field=models.CharField(choices=[('ONCE', 'однократно'), ('DAILY', 'ежедневно'), ('WEEKLY', 'еженедельно'), ('MONTHLY', 'ежемесячно')], default='ONCE', max_length=255, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('CREATED', 'создана'), ('LAUNCHED', 'запущена'), ('COMPLETED', 'завершена')], default='CREATED', max_length=255, verbose_name='статус рассылки'),
        ),
    ]
