# Generated by Django 4.2.2 on 2024-10-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_rename_sendtry_sendattempt_attempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendattempt',
            options={'verbose_name': 'попытка', 'verbose_name_plural': 'попытки'},
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.delivery', verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='last_attempt',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Дата последней попытки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='server_answer',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='status_attempt',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
    ]
