# Generated by Django 5.1 on 2024-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_sendattempt_options_sendattempt_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
