# Generated by Django 4.2.2 on 2024-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_alter_delivery_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendattempt',
            name='client',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
