# Generated by Django 4.2.2 on 2024-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_sendattempt_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='finish_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='конец рассылки'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='start_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало рассылки'),
        ),
    ]
