# Generated by Django 5.1 on 2024-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_delivery_finish_delivery_delivery_start_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='next_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата следующей рассылки'),
        ),
    ]
