# Generated by Django 4.2.2 on 2024-10-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_delivery_next_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribution.message', verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='start_delivery',
            field=models.DateTimeField(verbose_name='начало рассылки'),
        ),
    ]
