# Generated by Django 4.2.2 on 2024-10-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0009_alter_delivery_message_alter_delivery_start_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор рассылки'),
        ),
    ]
