# Generated by Django 4.2.2 on 2024-10-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_alter_delivery_options_client_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'permissions': [('can_view_deliveries', 'Can see all deliveries'), ('can_edit_is_active', 'Can deactivate a delivery')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
